server:
  servlet:
    context-path: /sys
#mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jobzp?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.shiyan.demo.beans
  global-config:
    id-type: 0
    db-column-underline: true
    capital-mode: true

logging:
  level:
    com:
      shiyan:
        demo:
          mapper: debug
