server:
  servlet:
    context-path: /sys
  port: 8888
#mysql
spring:
  datasource:
    url: jdbc:mysql://188.131.169.24:13306/jobzp?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    alicloud:
      ans:
        server-list: localhost
        server-port: 8080


mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.shiyan.demo.beans
  global-config:
    id-type: 0
    db-column-underline: true
    capital-mode: true

logging:
  level:
    com:
      shiyan:
        demo:
          mapper: debug



gwf:
  name: aaaaa